- README.md
- src/create-client.js
- src/forms.js
- src/responses.js
- src/themes.js
- src/utils.js
- src/workspaces.js
- tests/unit/forms.test.js
- tests/unit/responses.test.js
- tests/unit/themes.test.js
- tests/unit/utils.test.js
- tests/unit/workspaces.test.js
This PR fixes:
- Filter parameters for `forms.list`, `responses.list` are fixed
- `pageSize` is now camelcase, deprecated `page_size`
> Fix: parameters in requests

- README.md
Previous documentation had information for `forms.get`
> Fix forms.update documentation and link

- package.json
While browsing on NPM, I realized the homepage URL had a typo.
Here is a fix to it.
> Update package.json - Typo in Homepage URL

- README.md
The npm package I have for 1.3.0 have the webhook object listed as `webhooks`
> Fix typos in the documentation for webhooks

- README.md
- package.json
* Upgraded webpack and webpack-cli to fix error during build (TypeError: Cannot read property 'properties' of undefined caused by webpack/webpack#8082)
* Updated readme to include docs for Form.create
> Upgraded webpack to resolve build error and updated readme to include create

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/support-question.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/bugs.md
- .github/PULL_REQUEST_TEMPLATE/features.md
Add issue and pull request templates.
> Add issue and pull request templates

- README.md
- src/create-client.ts
- src/index.ts
- src/typeform-types.ts
- tests/unit/index.test.ts
Removes need for passing in token when constructing client, that way simple tasks like fetching public forms are easy. If a request requires a token, then the request would fail and the user would need to `catch` the failed request (which usually says a token is needed).
> feat(create-client): remove need for token

- .travis.yml
- package.json
- yarn.lock
Imports a shared travis configuration for the package. This shared travis configuration can be used to perform CI tasks common to all Typeform node libraries. We will use it as part of the NPM to GitHub package migration process.
> Use common travis config

- .travis.yml
This PR should makes `.travis.yml` to use shared config that enables publishing of npm packages to both registries: npm and github.
> fix: introduce shared travis config

- CODEOWNERS
- package.json
Change Codeowners to include @Typeform/partnerships instead of @typeform/atlantis
> fix: update codeowners wth  partnership team name

- src/create-client.ts
- tests/unit/create-client.test.ts
```
import { createClient } from '@typeform/api-client'
const clientWithApiBaseUrl = createClient({
token: 'abc',
apiBaseUrl: rainbowApi
})
```
> feat: add Api Base URL option to client

- src/workspaces.ts
Fixes return types for `Workspaces.add()` and `Workspaces.get()`, which were incorrectly set to `Webhook` instead of `Workspace`.
> fix: correct workspace add, get return types

- .github/workflows/ci-standard-checks.yml
Add ci-standard-checks workflow to improve standards adoption.
> chore(REACH-472): add ci-standard-checks workflow

- .github/workflows/ci-standard-checks.yml
- .travis.yml
- CONTRIBUTING.md
- README.md
> [REACH-487] Default branch "main"

- src/typeform-types.ts
The Create API allows for the logical operators 'and' and 'or' to be used to combine conditions for an action. This change updates the types to include an `AndOrOperator` type to reflect that.
https://developer.typeform.com/create/logic-jumps/#best-practices-for-logic-jumps
> fix(NOJIRA-123): fix Action.condition type

- .eslintignore
- README.md
- package.json
- rollup.config.js
- src/bin.ts
Add command line client that can be executed with `yarn typeform-api`.
Run in your own project or when this project is cloned locally:
```shell
yarn typeform-api <method> [params]
```
You need to supply personal token as `TF_TOKEN` env variable.
Example usage:
```shell
yarn typeform-api forms.list
yarn typeform-api forms.get '{uid:"abcd1234"}'
yarn typeform-api themes.list '{pageSize:3}'
```
> feat(REACH-717): add bin to run the client from command line

- README.md
- src/webhooks.ts
- tests/unit/webhooks.test.ts
I often need to change the state of a webhook.
The `update` function forces you to pass the URL pointing to the webhook.
`toggle` just turns on or off a webhook.
> feat(NOJIRA-123): Add Webhook toggle funcion

- README.md
- package.json
- src/auto-page-items.ts
- src/bin.ts
- src/forms.ts
- src/responses.ts
- src/themes.ts
- src/utils.ts
- src/workspaces.ts
- tests/unit/forms.test.ts
- tests/unit/responses.test.ts
- tests/unit/themes.test.ts
- tests/unit/workspaces.test.ts
- yarn.lock
When calling `workspaces.list`, `forms.list`, `themes.list` or `responses.list` you can supply `page: "auto"` and the library will fetch all items across all pages for you automatically.
It will fetch with maximum available `pageSize` (200 or 1000 for `responses.list`) to minimize number of requests.
Resolves #46
> feat(PR-40): auto-page list requests

- src/bin.ts
- src/create-client.ts
- src/typeform-types.ts
Use custom `Typeform.ApiError` class to throw error with more details.
Resolves #56
> feat(PR-40): throw custom error

- .eslintignore
- .gitignore
- README.md
- src/bin.ts
- src/themes.ts
- src/typeform-types.ts
- tests/unit/themes.test.ts
Update `Typeform.Theme` type to include new types from docs: https://www.typeform.com/developers/create/reference/create-theme/
Fix `theme.create` and `theme.update` methods to send payload to API.
Update the bin to load payload from a file: `params.json` as JSON or `params.js` as JavaScript object. It is easier to pass large payloads like this compared to passing it via command line.
Resolves #67
> feat(PR-40): update theme methods

- package.json
- tests/common.ts
- tests/unit/create-client.test.ts
- yarn.lock
In order to get 100% on secure dependencies we need to update axios, as it has a high severity vulnerability:
https://app.snyk.io/org/developer-relations-hax/project/0a05a01a-e24b-4b7b-af6e-509cbd9088c2
to do so, I also had to bump jest
> fix(TU-2535): secure dependencies, update axios

- .github/workflows/pr.yml
- .github/workflows/release.yml
- .releaserc
- package.json
- yarn.lock
When releasing with `semantic-release` it releases to one registry only, We need to run `npm publish` manually for the other one.
BREAKING CHANGES: Break support for Node 16 (end of life 2023-09-11) due to semantic-release dependency.
> fix(TU-2623): release to both npm and github registries

- src/forms.ts
- src/typeform-types.ts
- src/utils.ts
- src/workspaces.ts
The main goal of this PR was to fix up the type for `form.update` to allow patch updates. The current type definition only allows `data`  to be of type `Typeform.Form` which doesn't match the input required for `PATCH` operations. In the process of making the fix, I also made the following improvements to the `PATCH` type: 
1. Changed the type of `op` to a static list of operations currently supported by Typeform. I intentionally didn't add all of the [operations](https://jsonpatch.com/#operations) supported in JSON Patch as it does not seem the Typeform API supports all of those operations. 
2. I made the `PATCH` have a static list of paths depending on the endpoint. This one is definitely good for completion in editors, but does introduce a maintenance burden on the SDK as the list …
> feat(NOJIRA-123): Patch type improvements

- src/index.ts
Export the `clientConstructor` to allow wrapping the client (and extending it).
https://typeform.atlassian.net/browse/PLT-1549
> feat: export http client constructor
